GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inp1bGthcm5hZW5maHIiLCJuYW1lIjoiRmFocmkgSXp6dWRkaW4gWnVsa2FybmFlbiIsImVtYWlsIjoiZmFocmlAZ21haWwuY29tIiwiaWF0IjoxNjU5OTM4NzE0LCJleHAiOjE2NTk5Mzg3MzR9.U_XzcqPLmwFs-Jzfiyp4-rpqiERojPNCRBbri40va0Q

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "zulkarnaenfhr",
    "password": "123",
    "confirmPassword": "123",
    "email": "fahri@gmail.com",
    "name": "Fahri Izzuddin Zulkarnaen"
}

### 
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "zulkarnaenfhr",
    "password": "123"
}


###
GET http://localhost:5000/token

### logout user
DELETE http://localhost:5000/logout